language: node_js
node_js:
- node
notifications:
  slack:
    secure: AXtxg7oBZby19Cs7i5Tocf4XPZyn8h18mqQF15BI+IIucKiolhgUI4tcOC0O5OnUes+B7akY9f2GNDCL3qNkyC3KJQBMuNzLT3T1+9XVv93aoez+JcbPLtTSvcS8yBpF3SXYhxdZCW5POYwWu2H/Q4yOEfvolnnWx/7gDK9J0g5Cv/ACFqDXeVPvj29JQ0PdMjRaRyOXhFjg+Y9ftKsAGqIKiMPNL+5XtUYM3oo2RIi3hLPhZn2s3XsCl6uEj1fLcpkc906HsyR76UgEVKrITR2/jELiWbEXT5I1TDBHW3013Af8qwjmoxClQ3sbMyg5qOEu0mI7sAxT2st10HJRXXjjh/Wlo2UOfFNMXhRNOrKkb4XVGjK/Rt3vP50ODcy38gtzfN4AVaFq5TQTjU1xVAsDIf1D+oVf8xhuGgkMM3PcSPOoOeYg+/JhYsiMSjmCzUmYF1rRJaGH1OyF6gXsvv9b0BFaiXNOaDxQiaDIfIpK6/t13Wzr+e5qxm0bZk9yfqZCdYHGGgJBBdoZXLsNvl/f2UmgYA1s3SfTU24aLCqv5479MkdCLKG7kGXILw7F07yZuYWhYihDNDs6LMNwVYkGlTojoL/P2HZKeF7jgKsJSNe1fS7nLjiBzKWqF4AxdLncypskmKVVYLq9PiP1bjATCm56ImQvnMZQCOameOg=
